import react from 'react';

const ChessIcons = [
    {
        'row':1,
        'cell':1,
        'class':'black',
        'name': 'Rook',
        'icon':'&#9820;'
    },
    {
        'row':1,
        'cell':2,
        'class':'black',
        'name': 'Knight',
        'icon':'&#9822;'
    },
    {
        'row':1,
        'cell':3,
        'class':'black',
        'name': 'Bishop',
        'icon':'&#9821;'
    },
    {
        'row':1,
        'cell':4,
        'class':'black',
        'name': 'Queen',
        'icon':'&#9819;'
    },
    {
        'row':1,
        'cell':5,
        'class':'black',
        'name': 'King',
        'icon':'&#9818;'
    },
    {
        'row':1,
        'cell':6,
        'class':'black',
        'name': 'Bishop',
        'icon':'&#9821;'
    },
    {
        'row':1,
        'cell':7,
        'class':'black',
        'name': 'Knight',
        'icon':'&#9822;'
    },
    {
        'row':1,
        'cell':8,
        'class':'black',
        'name': 'Rook',
        'icon':'&#9820;'
    },
    {
        'row':2,
        'cell':1,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':2,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':3,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':4,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':5,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':6,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':7,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':8,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    
    {
        'row':2,
        'cell':1,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':2,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':3,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':4,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':5,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':6,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':7,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':2,
        'cell':8,
        'class':'black',
        'name':'Pawn',
        'icon':'&#9821;'
    },
    {
        'row':7,
        'cell':1,
        'class':'white',
        'name':'Pawn',
        'icon':'&#9817;'
    },
    {
        'row':7,
        'cell':2,
        'class':'white',
        'name':'Pawn',
        'icon':'&#9817;'
    },
    {
        'row':7,
        'cell':3,
        'class':'white',
        'name':'Pawn',
        'icon':'&#9817;'
    },
    {
        'row':7,
        'cell':4,
        'class':'white',
        'name':'Pawn',
        'icon':'&#9817;'
    },
    {
        'row':7,
        'cell':5,
        'class':'white',
        'name':'Pawn',
        'icon':'&#9817;'
    },
    {
        'row':7,
        'cell':6,
        'class':'white',
        'name':'Pawn',
        'icon':'&#9817;'
    },
    {
        'row':7,
        'cell':7,
        'class':'white',
        'name':'Pawn',
        'icon':'&#9817;'
    },
    {
        'row':7,
        'cell':8,
        'class':'white',
        'name':'Pawn',
        'icon':'&#9817;'
    },
    {
        'row':8,
        'cell':1,
        'class':'white',
        'name': 'Rook',
        'icon':'&#9814;'
    },
    {
        'row':8,
        'cell':2,
        'class':'white',
        'name': 'Knight',
        'icon':'&#9816;'
    },
    {
        'row':8,
        'cell':3,
        'class':'white',
        'name': 'Bishop',
        'icon':'&#9815;'
    },
    {
        'row':8,
        'cell':4,
        'class':'white',
        'name': 'Queen',
        'icon':'&#9813;'
    },
    {
        'row':8,
        'cell':5,
        'class':'white',
        'name': 'King',
        'icon':'&#9812;'
    },
    {
        'row':8,
        'cell':6,
        'class':'white',
        'name': 'Bishop',
        'icon':'&#9815;'
    },
    {
        'row':8,
        'cell':7,
        'class':'white',
        'name': 'Knight',
        'icon':'&#9816;'
    },
    {
        'row':8,
        'cell':8,
        'class':'white',
        'name': 'Rook',
        'icon':'&#9814;'
    },
];

export default ChessIcons;